{% set name = "arm-mango" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 368d55a432fdd14ed4d450d537169bdf99e7f390574965432ca6a5aba5df8ebb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - attrdict >=2.0.1
    - numpy >=1.17.0
    - python >=3.8
    - scikit-learn >=0.21.3
    - scipy >=1.4.1
    - tqdm >=4.36.1

test:
  imports:
    - mango
    - mango.domain
    - mango.optimizer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ARM-software/mango
  summary: Parallel bayesian optimization over complex search spaces
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
